site_name: "Li Siwei"
page-top-title: "Hello!I'm Li Siwei,welcome to my blog "
top-section-bg-text: "I'm pursuing AI studies with llm and nlp, and I've recently started working on cv research."
email: "lisiwwi1366@qq.com"
